### PR TITLE
RFC on "asides" in the book

### PR DESCRIPTION
**Pull request by rylev**

### CODE REVIEW

**Comment by steveklabnik** [comment]
I like this! :+1:  generally, but, there's still one question: what should they look like?

**Comment by sarahhodne** [comment]
Iʼd suggest asides are formatted as a box with a border around it, probably a different background color (the color change can act as a border in this case) and with a small mini-header, and if the browser window is wide enough it can float off to the right. This is roughly how Iʼve seen it done in most books that I can think of off the top of my head, and I think thatʼs pretty effective.

**Comment by rylev** [comment]
:+1: I agree. Generally I've seen the aside boxes with a grey background, but this may be due to paper publishing constraints. 

I like the mini-header: "By the way..." It's friendly and convey the right message I think. 

Does mdbook support arbitrary HTML and CSS? Not sure if anyone is interested in trying to implement this as a test run.

**Comment by varjmes** [comment]
Grey backgrounds aren't very accessible, so I'd go with a thick obvious border around the box :)

**Comment by azerupi** [comment]
I have styled the block quotes in the new version of mdBook. I based the style on the current Rust book block quotes. Maybe that could be used? It's a lot easier than including raw html:

```
>This would be an asside !
```

Let me know if that works! :)

> Does mdbook support arbitrary HTML and CSS?

Yes :)

**Comment by steveklabnik** [comment]
Let's do it!

**Pull request merged**
