### PR TITLE
Supplemental Book

### PR DESCRIPTION
**Pull request by rylev**
A proposal for a supplemental book. The more I thought about, the less I liked the idea of "a book on assembly programming". Assembly is a means not an end. We should use assembly as a way to explain concepts that are fundamental to understanding how computers work. 

Thoughts?

### CODE REVIEW

**Comment by steveklabnik** [comment]
I like this idea. :+1:

**Comment by varjmes** [comment]
What do we do with these RFCs? Do we merge them? I feel like the language used here is a bit unwieldy and a little inaccessible. If someone new to this book wanted to read the writing process/organisation behind it, they may struggle.

For reference, http://www.hemingwayapp.com/ puts this RFC text at "Grade 13" with over 50% of the sentences being hard to read.

I'm not intending to criticise, I'm just trying to figure out at what level these RFCs should be.

This is a good suggestion by the way, I'd love to have a separate book and as always would love to help wherever needed.

PS. intermezzOS is capitalised under the 'drawbacks' heading, which I don't think it should be?

**Comment by steveklabnik** [comment]
> What do we do with these RFCs? Do we merge them?

Leave a comment exactly like you did. If you think they're good, saying so is good, if you think they're bad, explaining why helps. 

>  I feel like the language used here is a bit unwieldy and a little inaccessible.

I think this is a good criticism. We should try to make RFCs as accessible as the project itself, as a whole.

> PS. intermezzOS is capitalised under the 'drawbacks' heading, which I don't think it should be?

Yeah, I've been writing it with a lower case `i` because I like the contrast with `OS` at the end.

**Comment by varjmes** [comment]
Awesome, thanks @steveklabnik :)

**Comment by steveklabnik** [comment]
No problem. RFC 1 was about the RFC system itself, a fun little bit of recursion: https://github.com/intermezzOS/rfcs/blob/master/text/0000-bootstrap.md

**Comment by rylev** [comment]
Sorry about the formal language here. I will rewrite the proposal to try to simplify it.

**Comment by rylev** [comment]
@Charlotteis check out the text now, and let me know if I was successful in simplifying the language. Thanks for your feedback!

**Comment by varjmes** [comment]
Wow, great work @rylev :sparkles:

**Comment by steveklabnik** [comment]
:shipit: :confetti_ball:

**Pull request merged**
